title: Writings Portfolio
email: your_email@example.com
description: >-  
  A curated collection of my writing projects and articles.
url: "" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Use Hyde theme via GitHub Pages remote theme capability
remote_theme: "poole/hyde"

# Collections definition
collections:
  projects:
    output: true
    permalink: /projects/:name/
  articles:
    output: true
    permalink: /projects/:project/:title/

# Defaults for front matter
defaults:
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: project
  - scope:
      path: "_articles"
      type: articles
    values:
      layout: article

# Build settings
markdown: kramdown
theme: null  # disable theme so remote_theme takes effect
plugins:
  - jekyll-feed
  - jekyll-remote-theme

paginate: 10
paginate_path: "/page:num/"
