title: My Writing Portfolio
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A collection of my writing projects and articles.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections to organize projects and their articles
collections:
  projects:
    output: true
    permalink: /projects/:name/
  articles:
    output: true
    permalink: /:collection/:name/

# Defaults so articles inherit layout and project taxonomy easily
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: articles
    values:
      layout: article

# Exclude folders we don't want Jekyll to process
exclude:
  - node_modules
  - project_plan_files
  - vendor
